# Generated by Django 2.2.6 on 2019-11-08 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_nab'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='nab',
            new_name='l_26',
        ),
    ]
