# Generated by Django 2.2.6 on 2019-11-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20191108_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='t8_9',
            fields=[
                ('halls', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('monday', models.IntegerField()),
                ('tuesday', models.IntegerField()),
                ('wednesday', models.IntegerField()),
                ('thursday', models.IntegerField()),
                ('friday', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='l_26',
        ),
    ]
