# Generated by Django 2.2.6 on 2019-11-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20191108_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='t10_11',
            fields=[
                ('halls', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('monday', models.IntegerField()),
                ('tuesday', models.IntegerField()),
                ('wednesday', models.IntegerField()),
                ('thursday', models.IntegerField()),
                ('friday', models.IntegerField()),
                ('types', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='t11_12',
            fields=[
                ('halls', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('monday', models.IntegerField()),
                ('tuesday', models.IntegerField()),
                ('wednesday', models.IntegerField()),
                ('thursday', models.IntegerField()),
                ('friday', models.IntegerField()),
                ('types', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='t12_1',
            fields=[
                ('halls', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('monday', models.IntegerField()),
                ('tuesday', models.IntegerField()),
                ('wednesday', models.IntegerField()),
                ('thursday', models.IntegerField()),
                ('friday', models.IntegerField()),
                ('types', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='t1_2',
            fields=[
                ('halls', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('monday', models.IntegerField()),
                ('tuesday', models.IntegerField()),
                ('wednesday', models.IntegerField()),
                ('thursday', models.IntegerField()),
                ('friday', models.IntegerField()),
                ('types', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='t2_3',
            fields=[
                ('halls', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('monday', models.IntegerField()),
                ('tuesday', models.IntegerField()),
                ('wednesday', models.IntegerField()),
                ('thursday', models.IntegerField()),
                ('friday', models.IntegerField()),
                ('types', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='t3_4',
            fields=[
                ('halls', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('monday', models.IntegerField()),
                ('tuesday', models.IntegerField()),
                ('wednesday', models.IntegerField()),
                ('thursday', models.IntegerField()),
                ('friday', models.IntegerField()),
                ('types', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='t4_5',
            fields=[
                ('halls', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('monday', models.IntegerField()),
                ('tuesday', models.IntegerField()),
                ('wednesday', models.IntegerField()),
                ('thursday', models.IntegerField()),
                ('friday', models.IntegerField()),
                ('types', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='t9_10',
            fields=[
                ('halls', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('monday', models.IntegerField()),
                ('tuesday', models.IntegerField()),
                ('wednesday', models.IntegerField()),
                ('thursday', models.IntegerField()),
                ('friday', models.IntegerField()),
                ('types', models.CharField(max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='t8_9',
            name='types',
            field=models.CharField(default='L', max_length=1),
        ),
    ]
