# Generated by Django 2.2.6 on 2019-11-08 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20191108_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='t10_11',
            name='block',
            field=models.CharField(default='NAB', max_length=20),
        ),
        migrations.AddField(
            model_name='t11_12',
            name='block',
            field=models.CharField(default='NAB', max_length=20),
        ),
        migrations.AddField(
            model_name='t12_1',
            name='block',
            field=models.CharField(default='NAB', max_length=20),
        ),
        migrations.AddField(
            model_name='t1_2',
            name='block',
            field=models.CharField(default='NAB', max_length=20),
        ),
        migrations.AddField(
            model_name='t2_3',
            name='block',
            field=models.CharField(default='NAB', max_length=20),
        ),
        migrations.AddField(
            model_name='t3_4',
            name='block',
            field=models.CharField(default='NAB', max_length=20),
        ),
        migrations.AddField(
            model_name='t4_5',
            name='block',
            field=models.CharField(default='NAB', max_length=20),
        ),
        migrations.AddField(
            model_name='t8_9',
            name='block',
            field=models.CharField(default='NAB', max_length=20),
        ),
        migrations.AddField(
            model_name='t9_10',
            name='block',
            field=models.CharField(default='NAB', max_length=20),
        ),
    ]
