# Generated by Django 2.2.6 on 2019-11-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20191109_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t10_11',
            name='friday',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AlterField(
            model_name='t10_11',
            name='monday',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AlterField(
            model_name='t10_11',
            name='thursday',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AlterField(
            model_name='t10_11',
            name='tuesday',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AlterField(
            model_name='t10_11',
            name='wednesday',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AlterField(
            model_name='t11_12',
            name='friday',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AlterField(
            model_name='t11_12',
            name='monday',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AlterField(
            model_name='t11_12',
            name='thursday',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AlterField(
            model_name='t11_12',
            name='tuesday',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AlterField(
            model_name='t11_12',
            name='wednesday',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AlterField(
            model_name='t12_1',
            name='friday',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AlterField(
            model_name='t12_1',
            name='monday',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AlterField(
            model_name='t12_1',
            name='thursday',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AlterField(
            model_name='t12_1',
            name='tuesday',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AlterField(
            model_name='t12_1',
            name='wednesday',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AlterField(
            model_name='t1_2',
            name='friday',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AlterField(
            model_name='t1_2',
            name='monday',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AlterField(
            model_name='t1_2',
            name='thursday',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AlterField(
            model_name='t1_2',
            name='tuesday',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AlterField(
            model_name='t1_2',
            name='wednesday',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AlterField(
            model_name='t2_3',
            name='friday',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AlterField(
            model_name='t2_3',
            name='monday',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AlterField(
            model_name='t2_3',
            name='thursday',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AlterField(
            model_name='t2_3',
            name='tuesday',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AlterField(
            model_name='t2_3',
            name='wednesday',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AlterField(
            model_name='t3_4',
            name='friday',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AlterField(
            model_name='t3_4',
            name='monday',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AlterField(
            model_name='t3_4',
            name='thursday',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AlterField(
            model_name='t3_4',
            name='tuesday',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AlterField(
            model_name='t3_4',
            name='wednesday',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AlterField(
            model_name='t4_5',
            name='friday',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AlterField(
            model_name='t4_5',
            name='monday',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AlterField(
            model_name='t4_5',
            name='thursday',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AlterField(
            model_name='t4_5',
            name='tuesday',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AlterField(
            model_name='t4_5',
            name='wednesday',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AlterField(
            model_name='t8_9',
            name='friday',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AlterField(
            model_name='t8_9',
            name='monday',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AlterField(
            model_name='t8_9',
            name='thursday',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AlterField(
            model_name='t8_9',
            name='tuesday',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AlterField(
            model_name='t8_9',
            name='wednesday',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AlterField(
            model_name='t9_10',
            name='friday',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AlterField(
            model_name='t9_10',
            name='monday',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AlterField(
            model_name='t9_10',
            name='thursday',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AlterField(
            model_name='t9_10',
            name='tuesday',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AlterField(
            model_name='t9_10',
            name='wednesday',
            field=models.CharField(default='empty', max_length=20),
        ),
    ]
