# Generated by Django 2.2.6 on 2019-11-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20191111_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='t8_9_copy',
            fields=[
                ('halls', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('block', models.CharField(default='NAB', max_length=20)),
                ('monday', models.CharField(default='empty', max_length=20)),
                ('tuesday', models.CharField(default='empty', max_length=20)),
                ('wednesday', models.CharField(default='empty', max_length=20)),
                ('thursday', models.CharField(default='empty', max_length=20)),
                ('friday', models.CharField(default='empty', max_length=20)),
                ('types', models.CharField(default='L', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='t9_10_copy',
            fields=[
                ('halls', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('block', models.CharField(default='NAB', max_length=20)),
                ('monday', models.CharField(default='empty', max_length=20)),
                ('tuesday', models.CharField(default='empty', max_length=20)),
                ('wednesday', models.CharField(default='empty', max_length=20)),
                ('thursday', models.CharField(default='empty', max_length=20)),
                ('friday', models.CharField(default='empty', max_length=20)),
                ('types', models.CharField(max_length=1)),
            ],
        ),
    ]
