# Generated by Django 2.2.6 on 2019-11-11 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_t8_9_copy_t9_10_copy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='t8_9_copy',
        ),
        migrations.DeleteModel(
            name='t9_10_copy',
        ),
    ]
