# Generated by Django 2.2.6 on 2019-11-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20191111_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='update',
            fields=[
                ('day', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('date', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
