# Generated by Django 2.2.6 on 2019-11-11 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='t10_11',
            name='friday_copy',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AddField(
            model_name='t10_11',
            name='monday_copy',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AddField(
            model_name='t10_11',
            name='thursday_copy',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AddField(
            model_name='t10_11',
            name='tuesday_copy',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AddField(
            model_name='t10_11',
            name='wednesday_copy',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AddField(
            model_name='t11_12',
            name='friday_copy',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AddField(
            model_name='t11_12',
            name='monday_copy',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AddField(
            model_name='t11_12',
            name='thursday_copy',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AddField(
            model_name='t11_12',
            name='tuesday_copy',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AddField(
            model_name='t11_12',
            name='wednesday_copy',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AddField(
            model_name='t1_2',
            name='friday_copy',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AddField(
            model_name='t1_2',
            name='monday_copy',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AddField(
            model_name='t1_2',
            name='thursday_copy',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AddField(
            model_name='t1_2',
            name='tuesday_copy',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AddField(
            model_name='t1_2',
            name='wednesday_copy',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AddField(
            model_name='t2_3',
            name='friday_copy',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AddField(
            model_name='t2_3',
            name='monday_copy',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AddField(
            model_name='t2_3',
            name='thursday_copy',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AddField(
            model_name='t2_3',
            name='tuesday_copy',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AddField(
            model_name='t2_3',
            name='wednesday_copy',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AddField(
            model_name='t3_4',
            name='friday_copy',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AddField(
            model_name='t3_4',
            name='monday_copy',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AddField(
            model_name='t3_4',
            name='thursday_copy',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AddField(
            model_name='t3_4',
            name='tuesday_copy',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AddField(
            model_name='t3_4',
            name='wednesday_copy',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AddField(
            model_name='t4_5',
            name='friday_copy',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AddField(
            model_name='t4_5',
            name='monday_copy',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AddField(
            model_name='t4_5',
            name='thursday_copy',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AddField(
            model_name='t4_5',
            name='tuesday_copy',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AddField(
            model_name='t4_5',
            name='wednesday_copy',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AddField(
            model_name='t9_10',
            name='friday_copy',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AddField(
            model_name='t9_10',
            name='monday_copy',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AddField(
            model_name='t9_10',
            name='thursday_copy',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AddField(
            model_name='t9_10',
            name='tuesday_copy',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AddField(
            model_name='t9_10',
            name='wednesday_copy',
            field=models.CharField(default='empty', max_length=20),
        ),
    ]
